### ISSUE TITLE
Tags aren't always fetched

### ISSUE THREAD

**Issue by infiniteluke** [finom/last-release-git#2]
Would it be a good idea to run `git fetch --tags` before https://github.com/finom/last-release-git/blob/master/src.js#L5?

Should this be part of the lib?

**Comment by finom** [comment]
@infiniteluke thank you but I don't think that the tool needs such side-effects.

**Comment by adrukh** [comment]
Struck the same issue - semantic release failed on travis due to invalid output of `git show-ref --tags`, which was empty. Resolved by adding `git fetch --tags` like so:
```
after_success:
  - git fetch --tags # needed to select new version off of latest git tag
  - npm run semantic-release
```
